### ISSUE TITLE
Script removes other items in ItemGroup

### ISSUE THREAD

**Issue by omidkrad** [endjin/git-hooks#2]
I ran `AutoFix-VisualStudioFiles.ps1` on our project and I noticed it removed all ItemGroup elements other than `<Reference>`, `<Compile>`, `<ProjectReference>`.

We have, for example `<Content>`, `<None>`, `<AppDesigner>`, `<EmbeddedResource>`, `<Page>` and some others.

**Comment by HowardvanRooijen** [comment]
It really shouldn't! Is there any chance you can supply a sample and I can use it to start a test suite?

**Comment by omidkrad** [comment]
I'm just looking at the code. This line `$itemGroup.RemoveAll() | Out-Null` seems to be the problem. I think this happens when `<ItemGroup>` contains mixed elements inside.

**Comment by omidkrad** [comment]
Something like this:

``` xml
<Project>
  <ItemGroup>
    <Reference Include="Antlr3.Runtime, Version=3.4.1.9004, Culture=neutral, PublicKeyToken=eb42632606e9261f, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(SolutionDir)packages\Antlr.3.4.1.9004\lib\Antlr3.Runtime.dll</HintPath>
    </Reference>
    <Content Include="Content\bootstrap.css" />
    <Page Include="Views\main.xaml" />
  </ItemGroup>
</Project>
```

**Comment by omidkrad** [comment]
Also it creates an extra file named `1` with content of `False` on the root of the repository.

**Comment by HowardvanRooijen** [comment]
I'm not sure how that's possible! We've not seen that behaviour in our internal usage!

**Comment by omidkrad** [comment]
Just copy the sample xml I gave in a `test.csproj` file, and run the script. It will retain `<Reference>` and remove `<Content>` and `<Page>`. I just submitted a fix that I think works. Thanks!

**Comment by omidkrad** [comment]
I'm just not sure why lines are not sorted correctly. For example I get this kind of order:

    <Reference Include="System.Core" />
    <Reference Include="System.Data" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Configuration" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System" />
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="WindowsBase" />
    <Reference Include="System.Xaml">

**Comment by omidkrad** [comment]
About the redundant file '`1`' I think it is git that is doing that. I don't know yet why, but it has to be related to the hook.

**Comment by omidkrad** [comment]
Another one: after running the script on a csproj file, try to open it as text/xml file in Visual Studio. VS shows a message saying that the line endings in the file are not consistent.

**Comment by kerslake** [comment]
Thanks Omid. I've used your scenarios fixed so far to start a suite of tests using Pester. We should continue to bolster this for the existing untested scenarios and any new issues.

I haven't been able to reproduce the file '1' being generated. If you can consistently reproduce and work it out or the steps required that would be great. I also haven't looked at the inconsistent line endings yet. Should probably make new issues for them anyway!

**Comment by omidkrad** [comment]
OK I opened #5 to track the line ending issue.
